name: movies_and_stars
description: Cool movie app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  data:
    path: packages/data
  presentation:
    path: packages/presentation

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Semibold.otf
        - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Bold.otf
