name: presentation
description: presentation layer to movies_and_stars project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  domain:
    path: ../domain
  flutter_svg: ^1.1.4
  shimmer: ^2.0.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  intl_utils: ^2.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
flutter_intl:
  enabled: true
  class_name: SM
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated_localization
  use_deferred_loading: false
