name: build_pr_debug_f_d

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - master

jobs:
  build_debug_send_to_firebase_destribution:
    name: DebugAPKtoFD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter --version
      - name: Flutter upgrade
        run: flutter upgrade
      - name: AppKeys
        run: |
          touch secrets.json
          echo "{" >> secrets.json
          echo " \"apiKeyTRAKT\": \"${{secrets.API_KEY_TRAKT}}\",\" >> secrets.json
          echo " \"apiKeyOMDB\": \"${{secrets.API_KEY_OMDB}}\",\" >> secrets.json
          echo " \"apiKeyTMDB\": \"${{secrets.API_KEY_TMDB}}\",\" >> secrets.json
          echo " \"facebook_app_id\": \"${{secrets.FACEBOOK_APP_ID}}\",\" >> secrets.json
          echo " \"fb_login_protocol_scheme\": \"${{secrets.FACEBOOK_CLIENT_TOKEN}}\",\" >> secrets.json
          echo " \"facebook_client_token\": \"${{secrets.FB_LOGIN_PROTOCOL_SCHEME}}\"\" >> secrets.json
          echo "}" >> secrets.json
          cat secrets.json
      - name: PresentationDependencies
        run: |
          flutter pub get
          flutter gen-l10n
        working-directory: packages/presentation
      - name: DataDependencies
        run: |
          flutter pub get
        working-directory: packages/data
      - name: DomainDependencies
        run: |
          flutter pub get
        working-directory: packages/domain
      - name: Build APK
        run: flutter build apk --debug
      - name: Debug version push to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.5
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          stoken: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: build/app/outputs/flutter-apk/app-debug.apk
